Website/MiSpyWebAppMVC-master/MiSpyWebAppMVC-master/MiSpyWebAppMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MiSpyWebAppMVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MiSpyWebAppMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Download()
        {
            return View();
        }

        public IActionResult Help()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Website/MiSpyWebAppMVC-master/MiSpyWebAppMVC-master/MiSpyWebAppMVC/Controllers/MonitorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MiSpyWebAppMVC.Data;
using MiSpyWebAppMVC.Models;

namespace MiSpyWebAppMVC.Controllers
{
    [Authorize] 
    public class MonitorController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MonitorController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MonitorManager
        public async Task<IActionResult> Index(int? pageNumber)    
        {
            var events = from e in _context.LoggedEvent
                         where e.UserId == User.Identity.Name
                         select e;

            int pageSize = 10;
            return View(await PaginatedList<LoggedEvent>.CreateAsync(events.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        //GET: Monitor/EventDetails/1
        public async Task<IActionResult> EventDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detailedEvent = await _context.LoggedEvent
                .FirstOrDefaultAsync(e => e.Id == id);

            if (detailedEvent == null)
            {
                return NotFound();
            }

            return View(detailedEvent);
        }
    }
}

Website/MiSpyWebAppMVC-master/MiSpyWebAppMVC-master/MiSpyWebAppMVC/Views/Home/Download.cshtml
@{
    ViewData["Title"] = "Download";
}

<div class="text-center">
    <br />
    <div class="container" id="indexSideLeft">
        <div class="row">
            <div class="col-sm-6">
                <h1>Download</h1>
                <br />
                <h3>To start viewing typed data in our reporting page, download our client to collect typed entries to monitor</h3>
                <br />
                <a class="btn btn-light" asp-page="">Download for Windows</a> <a class="btn btn-light" asp-page="">Download for MacOSX</a>
                <br />
                <br />
                <p>Runs on: <img src="~/images/windowslogo.jpg" width="35" height="35" alt="windowslogo" /><img src="~/images/applelogo.png" width="30" height="30" alt="applelogo" /></p>
            </div>
            <div class="col-sm-6">
                <img src="~/images/MiSpy_Logo.png" alt="MiSpyLogo" id="downloadCentreImg" />
            </div>
        </div>
        <br />
        <!-- New Row -->
        <div class="row">
            <div class="col-sm-6">
                <br />
                <h1>Set up Steps:</h1>
                <br />
                <br />
                <h3>Follow the installation steps as instructed by the installer:</h3>
            </div>
            <div class="col-sm-6">
                <img src="~/images/installguideimg/dummyinstallwindow.png" width="500" height="350" alt="Installation Guide Image" />
            </div>
        </div>
        <br />
        <br />
        <!-- New Row -->
        <div class="row">
            <div class="col-sm-6">
                <img src="~/images/installguideimg/windowsstartmenu.png" width="400" height="300" alt="Start Menu Image" />
            </div>
            <div class="col-sm-6">
                <br />
                <h1>Run the Application</h1>
                <br />
                <br />
                <h3>Once the Installation is successful, run the application. This can be found in your Start Menu on your Operating System</h3>
            </div>
        </div>
        <br />
        <br />
        <!-- New Row -->
        <div class="row">
            <div class="col-sm-6">
                <br />
                <h1>Log in:</h1>
                <br />
                <br />
                <h3>Log in using your Mi-Spy credentials, we'll then start sending logged events to your account to view using our reporting page!</h3>
            </div>
            <div class="col-sm-6">
                <img src="~/images/installguideimg/dummyloginscreen.jpg" width="400" height="300" alt="Login Guide Image" />
            </div>
        </div>
        <br />
    </div>

</div>

Website/MiSpyWebAppMVC-master/MiSpyWebAppMVC-master/MiSpyWebAppMVC/Views/Home/Help.cshtml
@{
    ViewData["Title"] = "Help";
}

<div class="text-center">
    <br />
    <div class="container" id="indexSideLeft">
        <div class="row">
            <div class="col-6">
                <h1>Help</h1>
                <br />
                <h3>Help, Support and Frequently Asked Questions about the Mi-Spy System</h3>
                <br />
                <br />
            </div>
            <div class="col-6">
                <!--Image or extra information goes here-->
                <img src="~/images/helpPageImg.png" width="450" height="200" alt="helpimg" />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col">
                <!--Accordion with Questions and Answers-->
                <h1>Frequently Asked Questions</h1>
                <br />
                <div class="accordion" id="helpPageAccordion">
                    <!-- Question -->
                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <h2 class="mb-0">
                                <button class="btn btn-link btn-block text-left" id="accordionQuestion" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    Why is my report empty?
                                </button>
                            </h2>
                        </div>
                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#helpPageAccordion">
                            <div class="card-body" id="accordionAnswer">
                                <a id="coloredBullet">-</a> The Report will show entries when the PC Application is installed and you've signed in. You can download the PC Companion from our site: <a class="btn btn-light btn-sm" asp-action="Download">Download</a>
                            </div>
                        </div>
                    </div>
                    <!-- Question -->
                    <div class="card">
                        <div class="card-header" id="headingTwo">
                            <h2 class="mb-0">
                                <button class="btn btn-link btn-block text-left collapsed" id="accordionQuestion" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                    Collapsible Group Item #2
                                </button>
                            </h2>
                        </div>
                        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#helpPageAccordion">
                            <div class="card-body" id="accordionAnswer">
                                <a id="coloredBullet">-</a> Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                            </div>
                        </div>
                    </div>
                    <!-- Question -->
                    <div class="card">
                        <div class="card-header" id="headingThree">
                            <h2 class="mb-0">
                                <button class="btn btn-link btn-block text-left collapsed" id="accordionQuestion" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                    Collapsible Group Item #3
                                </button>
                            </h2>
                        </div>
                        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#helpPageAccordion">
                            <div class="card-body" id="accordionAnswer">
                                <a id="coloredBullet">-</a> Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br />
    </div>
</div>

Website/MiSpyWebAppMVC-master/MiSpyWebAppMVC-master/MiSpyWebAppMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<div class="text-center">
    <br />
    <div class="container" id="indexSideLeft">
        <div class="row">
            <div class="col-6">
                <h1>Simple reports for parental review</h1>
                <br />
                <h3>View typed data in a simple reporting page.</h3>
                <br />
                <a class="btn btn-light" asp-controller="Monitor" asp-action="Index">Show my report</a> <a class="btn btn-outline-dark" asp-area="Identity" asp-page="/Account/Register">START FOR FREE</a>
                <br />
                <br />
                <p>Runs on: <img src="~/images/windowslogo.jpg" width="30" height="30" alt="windowslogo" /></p>
            </div>
            <div class="col-6">
                <!--Image or poster goes here, maybe extra information-->
            </div>
        </div>
    </div>

</div>